### PR TITLE
Fix end effects for AFT rotating clockwise

### LINKED ISSUE #247: endEffects returns error in CW rotation
Upon running the provided axial flow tutorial with
axis (1 0 0);
I get the following error related to endEffects:

```
PIMPLE: iteration 1
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  acos in "/lib/x86_64-linux-gnu/libm.so.6"
#4  Foam::fv::axialFlowTurbineALSource::calcEndEffects() at ??:?
#5  Foam::fv::axialFlowTurbineALSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#6  ? at ??:?
#7  ? at ??:?
#8  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#9  ? at ??:?
```

Active model is

```
        endEffects
        {
            active          on;
            endEffectsModel Glauert; // Glauert || Shen || liftingLine
            GlauertCoeffs
            {
                tipEffects  on;
                rootEffects on;
            }
        }
```
same as in the axialFlowTurbineAL tutorial. The code runs without error with endEffects active off.

### PR DESCRIPTION
**Pull request by petebachant**
When finished, resolves #247.

### CODE REVIEW

**Comment by petebachant** [comment]
There seems to be a geometry issue for clockwise rotation, which could be related to the frame of reference for camber.

File: src/fvOptions/axialFlowTurbineALSource/axialFlowTurbineALSource.C [hunk 1]
```diff
@@ -182,29 +182,34 @@ void Foam::fv::axialFlowTurbineALSource::createBlades()
...
+            // Set chord length
+            elementGeometry[j][2][0] = chordLength;
+
             // Set chord mount
             elementGeometry[j][4][0] = chordMount;
 
-            // Set pitch
-            elementGeometry[j][5][0] = -pitch;
+            // Set element pitch or twist
+            elementGeometry[j][5][0] = pitch;
```
Comment (petebachant) [inline src/fvOptions/axialFlowTurbineALSource/axialFlowTurbineALSource.C]: Need to check this sign change here. Seems like it's correct based on the geometry though.
